/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.eeob.ndrasistencias.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pe.eeob.ndrasistencias.controller.ApoderadoController;
import pe.eeob.ndrasistencias.controller.EstudianteController;
import pe.eeob.ndrasistencias.domain.Estudiante;
import pe.eeob.ndrasistencias.util.Dialogo;
import pe.eeob.ndrasistencias.util.Ndr;

/**
 *
 * @author ErickOre
 */
public class EditarEliminarlEstudianteView extends javax.swing.JDialog {
    private String accion;
    /**
     * Creates new form EditarEliminarlEstudianteView
     */
    public EditarEliminarlEstudianteView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

  public void setAccion(String accion) {
    this.accion = accion;
    establecerTitulo();
    habilitarControles();
    // Boton
    btnProcesar.setText(accion);    
  }

  private void establecerTitulo() {
    String titulo = "%s ESTUDIANTE";
    titulo = String.format(titulo, accion);
    this.setTitle(titulo);
  }

  private void habilitarControles() {
    txtPaterno.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
    txtMaterno.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
    txtNombre.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
    txtEdad.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
    txtDistrito.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
    comboDniApoderado.setEnabled(!accion.equals(Ndr.CRUD_ELIMINAR));
  }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboDniApoderado = new javax.swing.JComboBox<>();
        txtDni = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        txtMaterno = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("APELLIDO MATERNO:");

        jLabel7.setText("DNI APODERADO:");

        comboDniApoderado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDniApoderado.setEnabled(false);

        txtDni.setEnabled(false);

        txtPaterno.setEnabled(false);

        btnProcesar.setText("EDITAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        txtMaterno.setEnabled(false);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtNombre.setEnabled(false);

        jLabel1.setText("DNI:");

        txtEdad.setEnabled(false);

        jLabel5.setText("EDAD:");

        txtDistrito.setEnabled(false);

        jLabel2.setText("APELLIDO PATERNO:");

        jLabel4.setText("NOMBRE:");

        jLabel6.setText("DISTRITO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtPaterno)
                            .addComponent(txtMaterno)
                            .addComponent(txtNombre)
                            .addComponent(txtEdad)
                            .addComponent(txtDistrito)
                            .addComponent(comboDniApoderado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnProcesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboDniApoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnSalir))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        Estudiante bean = new Estudiante();
        bean.setDni(txtDni.getText());
        bean.setPaterno(txtPaterno.getText());
        bean.setMaterno(txtMaterno.getText());
        bean.setNombre(txtNombre.getText());
        bean.setEdad(txtEdad.getText());
        bean.setDistrito(txtDistrito.getText());
        bean.setDni_apoderado(comboDniApoderado.getSelectedItem().toString());
        EstudianteController control = new EstudianteController();
        control.grabar(bean,accion);
        if ( accion == "EDITAR"){
        JOptionPane.showMessageDialog(null, "Estudiante Actualizado!");
        } else {
        JOptionPane.showMessageDialog(null, "Estudiante Eliminado!");    
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEliminarlEstudianteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEliminarlEstudianteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEliminarlEstudianteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEliminarlEstudianteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarEliminarlEstudianteView dialog = new EditarEliminarlEstudianteView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboDniApoderado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables

  private void llenarCombo(List<String> ls) {
        DefaultComboBoxModel combo;
        combo = (DefaultComboBoxModel) comboDniApoderado.getModel();
        combo.removeAllElements();
        for ( String c : ls) {
         String row = c;
         combo.addElement(row);        
        }  
  }    

    /**
     *
     * @param bean
     */
    public void setBean(Estudiante bean) {

        // Inicializando combo box
        try {
            ApoderadoController cr = new ApoderadoController();
            llenarCombo(cr.getDniApos());
        } catch (Exception e) {
            Dialogo.error(rootPane, e.getMessage());
        }
        comboDniApoderado.setSelectedIndex(-1);        

        txtDni.setText(bean.getDni());
        txtPaterno.setText(bean.getPaterno());
        txtMaterno.setText(bean.getMaterno());
        txtNombre.setText(bean.getNombre());
        txtEdad.setText(bean.getEdad());
        txtDistrito.setText(bean.getDistrito());

        int n = comboDniApoderado.getItemCount();
        for (int i=0;i<n;i++){
            String s = comboDniApoderado.getItemAt(i).toString();
            if(s.equals(bean.getDni_apoderado())){
                comboDniApoderado.setSelectedIndex(i);
            }
        }

    }

}
