/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.eeob.ndrasistencias.view;

import java.awt.Component;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import pe.eeob.ndrasistencias.domain.Estudiante;
import pe.eeob.ndrasistencias.domain.Maestro;
import pe.eeob.ndrasistencias.util.Memoria;
import pe.eeob.ndrasistencias.util.Ndr;

/**
 *
 * @author ErickOre
 */
public class FormularioPrincipal extends javax.swing.JFrame {
   
    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        establecerTitulo();
    }
    private void establecerTitulo() {
        String titulo = "NDR";
        Maestro mst = (Maestro) Memoria.get("usuario");
        titulo += " [Usuario: " + mst.getUsuario() + "]";
        titulo += " [Url: " + Memoria.getS1();
        this.setTitle(titulo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuTabla = new javax.swing.JMenu();
        menuTablaApoderado = new javax.swing.JMenuItem();
        menuTablaCurso = new javax.swing.JMenuItem();
        menuMantEstudiante = new javax.swing.JMenu();
        menuMantEstudianteAgregar = new javax.swing.JMenuItem();
        menuMantEstudianteEE = new javax.swing.JMenuItem();
        menuMantMaes = new javax.swing.JMenu();
        menuMaesAgregar = new javax.swing.JMenuItem();
        menuMaesEE = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasApoderado = new javax.swing.JMenuItem();
        menuConsultasAula = new javax.swing.JMenuItem();
        menuConsultasCurso = new javax.swing.JMenuItem();
        menuConsultasEscuela = new javax.swing.JMenuItem();
        menuConsultasEstudiante = new javax.swing.JMenuItem();
        menuConsultasMaestro = new javax.swing.JMenuItem();
        menuConsultasSede = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArchivo.add(jMenuItem1);

        jMenuBar1.add(menuArchivo);

        menuTabla.setText("Mantenimiento");
        menuTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaActionPerformed(evt);
            }
        });

        menuTablaApoderado.setText("Apoderado");
        menuTabla.add(menuTablaApoderado);

        menuTablaCurso.setText("Curso");
        menuTabla.add(menuTablaCurso);

        menuMantEstudiante.setText("Estudiante");

        menuMantEstudianteAgregar.setText("Agregar");
        menuMantEstudianteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantEstudianteAgregarActionPerformed(evt);
            }
        });
        menuMantEstudiante.add(menuMantEstudianteAgregar);

        menuMantEstudianteEE.setText("Editar / Eliminar");
        menuMantEstudianteEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantEstudianteEEActionPerformed(evt);
            }
        });
        menuMantEstudiante.add(menuMantEstudianteEE);

        menuTabla.add(menuMantEstudiante);

        menuMantMaes.setText("Maestro");

        menuMaesAgregar.setText("Agregar");
        menuMaesAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaesAgregarActionPerformed(evt);
            }
        });
        menuMantMaes.add(menuMaesAgregar);

        menuMaesEE.setText("Editar/Eliminar");
        menuMantMaes.add(menuMaesEE);

        menuTabla.add(menuMantMaes);

        jMenuBar1.add(menuTabla);

        menuConsultas.setText("Consultas");

        menuConsultasApoderado.setText("Apoderado");
        menuConsultasApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasApoderadoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasApoderado);

        menuConsultasAula.setText("Aula");
        menuConsultasAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasAulaActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasAula);

        menuConsultasCurso.setText("Curso");
        menuConsultasCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasCursoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasCurso);

        menuConsultasEscuela.setText("Escuela");
        menuConsultasEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasEscuelaActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasEscuela);

        menuConsultasEstudiante.setText("Estudiante");
        menuConsultasEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasEstudianteActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasEstudiante);

        menuConsultasMaestro.setText("Maestro");
        menuConsultasMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasMaestroActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasMaestro);

        menuConsultasSede.setText("Sede");
        menuConsultasSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasSedeActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasSede);

        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuConsultasSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasSedeActionPerformed
        cargarFormulario(ConsultaSedeView.class);
    }//GEN-LAST:event_menuConsultasSedeActionPerformed

    private void menuConsultasAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasAulaActionPerformed
        cargarFormulario(ConsultaAulaView.class);
    }//GEN-LAST:event_menuConsultasAulaActionPerformed

    private void menuConsultasEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasEscuelaActionPerformed
        cargarFormulario(ConsultaEscuelaView.class);
    }//GEN-LAST:event_menuConsultasEscuelaActionPerformed

    private void menuConsultasMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasMaestroActionPerformed
        cargarFormulario(ConsultaMaestrosView.class);
    }//GEN-LAST:event_menuConsultasMaestroActionPerformed

    private void menuConsultasApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasApoderadoActionPerformed
        cargarFormulario(ConsultaApoderadoView.class);
    }//GEN-LAST:event_menuConsultasApoderadoActionPerformed

    private void menuConsultasEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasEstudianteActionPerformed
        cargarFormulario(ConsultaEstudianteView.class);
    }//GEN-LAST:event_menuConsultasEstudianteActionPerformed

    private void menuConsultasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasCursoActionPerformed
        cargarFormulario(ConsultaCursoView.class);
    }//GEN-LAST:event_menuConsultasCursoActionPerformed

    private void menuTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTablaActionPerformed

    private void menuMantEstudianteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantEstudianteAgregarActionPerformed
        Estudiante bean = new Estudiante();
        try{
            MantEstView view = new MantEstView();
            view.setBean(bean);
            view.setAccion(Ndr.CRUD_NUEVO);       
            view.setVisible(true);        
            view.setSelected(true);
            desktopPane.add(view);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_menuMantEstudianteAgregarActionPerformed

    private void menuMantEstudianteEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantEstudianteEEActionPerformed
        Estudiante bean = new Estudiante();
        try{
            ConsultaEstudianteView view = new ConsultaEstudianteView();
            view.setAccion(Ndr.CRUD_EDITAR);       
            view.setVisible(true);        
            view.setSelected(true);
            desktopPane.add(view);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_menuMantEstudianteEEActionPerformed

    private void menuMaesAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaesAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMaesAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasApoderado;
    private javax.swing.JMenuItem menuConsultasAula;
    private javax.swing.JMenuItem menuConsultasCurso;
    private javax.swing.JMenuItem menuConsultasEscuela;
    private javax.swing.JMenuItem menuConsultasEstudiante;
    private javax.swing.JMenuItem menuConsultasMaestro;
    private javax.swing.JMenuItem menuConsultasSede;
    private javax.swing.JMenuItem menuMaesAgregar;
    private javax.swing.JMenuItem menuMaesEE;
    private javax.swing.JMenu menuMantEstudiante;
    private javax.swing.JMenuItem menuMantEstudianteAgregar;
    private javax.swing.JMenuItem menuMantEstudianteEE;
    private javax.swing.JMenu menuMantMaes;
    private javax.swing.JMenu menuTabla;
    private javax.swing.JMenuItem menuTablaApoderado;
    private javax.swing.JMenuItem menuTablaCurso;
    // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      // Variable
      JInternalFrame view;
      // Buscar instancia
      view = buscarInstancia(aClass);
      // Crear instancia
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
      }
      // Mostrar formulario
      view.setVisible(true);
      view.setSelected(true);
    } catch (Exception e) {
    }
  }

  private JInternalFrame buscarInstancia(Class<?> aClass) {
    JInternalFrame view = null;
    for (JInternalFrame form : desktopPane.getAllFrames()) {
      if (aClass.isInstance(form)) {
        view = form;
        break;
      }
    }
    return view;
  }

}
