/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.proyecto.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;

import pe.egcc.proyecto.entity.Producto;
import pe.egcc.proyecto.model.ProductoModel;
import pe.egcc.proyecto.util.Dialogo;
import pe.egcc.proyecto.util.Memoria;



/**
 *
 * @author Usuario
 */
public class MantProductoView extends javax.swing.JInternalFrame {

 
    /**
     * Creates new form MaintProductoView
     */
    public MantProductoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        lblMensaje = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BUSQUEDA DEL PRODUCTO");

        jLabel1.setText("Nombre del producto:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyecto/img/buscar.gif"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyecto/img/new.png"))); // NOI18N
        btnNuevo.setActionCommand("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyecto/img/edit.png"))); // NOI18N
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/proyecto/img/delete.png"))); // NOI18N
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      buscarProductos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       EditarProductoView view = new EditarProductoView(null, true);
		view.setId(0);/*
		 * como es nuevo le pasamos "0"
		 */
		Memoria.put("producto", null);
		view.setVisible(true);
		if (Memoria.get("producto") != null) {
			agregarProducto((Producto) Memoria.get("producto"));
		}
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     int fila = tblData.getSelectedRow();
		int id = (Integer) tblData.getValueAt(fila, 0);
		EditarProductoView view = new EditarProductoView(null, true);
		view.setId(id);/*
		 * como es nuevo le pasamos "0"
		 */
		Memoria.put("producto", null);
		view.setVisible(true);
		if (Memoria.get("producto") != null) {
			actualizarFila(fila, (Producto) Memoria.get("producto"));
		}
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       try {
			int fila = tblData.getSelectedRow();
			if (fila > -1) {
				int id = (Integer) tblData.getValueAt(fila, 0);
				String pregunta = "¿Está seguro de elimina el producto " + id + "?";
				if (Dialogo.confirmYesNo(rootPane, pregunta) == Dialogo.YES_OPTION) {
					ProductoModel model = new ProductoModel();
					model.eliminar(id);
					eliminarFila(fila);
				}
			}
		} catch (Exception e) {
			Dialogo.error(rootPane, e.getMessage());
		}
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
 
private void buscarProductos() {
		try {
			ProductoModel model = new ProductoModel();
			String nombre = txtNombre.getText();
			limpiarTabla();
			desactivarBotones();
			if (!nombre.isEmpty()) {
				List<Producto> lista = model.buscar(nombre);
				int filas = 0;
				if (lista != null && !lista.isEmpty()) {
					filas = lista.size();
					mostrarLista(lista);
					activarBotones();
				}
				lblMensaje.setText(filas + " filas encontradas.");
			} else {
				lblMensaje.setText("Ingrese por lo menos un caracter.");
			}
		} catch (Exception e) {
			Dialogo.error(rootPane, e.getMessage());
		}
	}

	private void limpiarTabla() {
		DefaultTableModel model = (DefaultTableModel) tblData.getModel();
		model.setRowCount(0);
	}

	private void mostrarLista(List<Producto> lista) {
		DefaultTableModel model = (DefaultTableModel) tblData.getModel();
		for (Producto p : lista) {
			Object[] rowData = {p.getIdprod(), p.getNombre(),
				p.getIdcat(), p.getPrecio(), p.getStock()};
			model.addRow(rowData);
		}
		tblData.setRowSelectionInterval(0, 0);
	}

	private void desactivarBotones() {
		btnEditar.setEnabled(false);
		btnEliminar.setEnabled(false);
	}

	private void activarBotones() {
		btnEditar.setEnabled(true);
		btnEliminar.setEnabled(true);
	}

	private void actualizarFila(int fila, Producto p) {
		tblData.setValueAt(p.getNombre(), fila, 1);
		tblData.setValueAt(p.getIdcat(), fila, 2);
		tblData.setValueAt(p.getPrecio(), fila, 3);
		tblData.setValueAt(p.getStock(), fila, 4);
	}

	private void agregarProducto(Producto p) {
		DefaultTableModel model = (DefaultTableModel) tblData.getModel();
		Object[] rowData = {p.getIdprod(), p.getNombre(),
			p.getIdcat(), p.getPrecio(), p.getStock()};
		model.addRow(rowData);
	}

	private void eliminarFila(int index) {
		DefaultTableModel model = (DefaultTableModel) tblData.getModel();
		model.removeRow(index);
		int ultimo_indice = model.getRowCount() - 1;
		if (model.getRowCount() > 0) {
			if (index > ultimo_indice) {
				index = ultimo_indice;
			}
			tblData.setRowSelectionInterval(index, index);
			activarBotones();
		} else {
			desactivarBotones();
		}
	}
  
}

