CREATE USER Proyecto IDENTIFIED BY Moreno;
GRANT connect, resource TO Proyecto;
CONNECT Proyecto/Moreno;
CREATE TABLE "USUARIO" ("USUARIO" VARCHAR2(20), "CONTRASEÑA" VARCHAR2(20), "PATERNO" VARCHAR2(30), "MATERNO" VARCHAR2(30), "NOMBRE" VARCHAR2(30), "DNI" VARCHAR2(8), "TELEFONO" VARCHAR2(12), "DIRECCION" VARCHAR2(50), "EMAIL" VARCHAR2(30), "TIPO" VARCHAR2(1), "IMAGEN" BLOB);
Insert into USUARIO (USUARIO,CONTRASEÑA,PATERNO,MATERNO,NOMBRE,DNI,TELEFONO,DIRECCION,EMAIL,TIPO) values ('Moreno','Ms','MORENO','SAAVEDRA','MARCO','72396369','931385372','21 de Abril','moreno_s@outlook.com','1');
Insert into USUARIO (USUARIO,CONTRASEÑA,PATERNO,MATERNO,NOMBRE,DNI,TELEFONO,DIRECCION,EMAIL,TIPO) values ('Js','123','SUAREZ','LOPEZ','JUAN','75169485','980035702','Lima','juan_sl@hotmail.com','2');
Insert into USUARIO (USUARIO,CONTRASEÑA,PATERNO,MATERNO,NOMBRE,DNI,TELEFONO,DIRECCION,EMAIL,TIPO) values ('Campos','Campos1','CAMPOS','AMAYA','LEO YAIR','78495326','943491849','2 DE MAYO','campos1@hotmail.com','2');
Insert into USUARIO (USUARIO,CONTRASEÑA,PATERNO,MATERNO,NOMBRE,DNI,TELEFONO,DIRECCION,EMAIL,TIPO) values ('Torres','12345','TORRES','MARTINEZ','LUIS','45781694','326003','CALLAO','tmartinez@gmail.com','2');
