/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.eurekacs.view;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import pe.egcc.eurekacs.controller.CuentaController;
import pe.egcc.eurekacs.util.Dialogo;
import pe.egcc.eurekacs.util.ReportViewInternal;

/**
 *
 * @author Gustavo Coronel
 */
public class RepoMovView extends javax.swing.JInternalFrame {

  /**
   * Creates new form RepoMovView
   */
  public RepoMovView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    btnConsultar = new javax.swing.JButton();
    panelRepo = new javax.swing.JPanel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    jLabel1.setText("Cuenta:");

    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelRepoLayout = new javax.swing.GroupLayout(panelRepo);
    panelRepo.setLayout(panelRepoLayout);
    panelRepoLayout.setHorizontalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelRepoLayout.setVerticalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 511, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnConsultar)
        .addContainerGap(447, Short.MAX_VALUE))
      .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(txtCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
    try {
      // Obteniendo Datos
      CuentaController control = new CuentaController();
      List<Map<String, ?>> lista;
      lista = control.traerMovimientos(txtCuenta.getText());
      JRMapCollectionDataSource jrData;
      jrData = new JRMapCollectionDataSource(lista);
      // Parametros
      Map pars = new HashMap();
      // El reporte
      String fileRepo = "/pe/egcc/eurekacs/reports/repoMovimientos.jasper";
      InputStream ioRepo = Class.class.getResourceAsStream(fileRepo);
      JasperPrint jpRepo;
      jpRepo = JasperFillManager.fillReport(ioRepo, pars, jrData);
      // Visualizando el Reporte
      ReportViewInternal viewer = new ReportViewInternal("MOVIMIENTOS");
      viewer.setReporte(jpRepo);
      viewer.setTitle("MOVIMIENTOS");
      panelRepo.removeAll();
      panelRepo.add(viewer);
      viewer.setVisible(true);
      viewer.setMaximum(true);
      viewer.setClosable(false);
      viewer.setIconifiable(false);
      viewer.setMaximizable(false);
      viewer.setResizable(false);
    } catch (Exception ex) {
      Dialogo.error(null, ex.getMessage());
    }
  }//GEN-LAST:event_btnConsultarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConsultar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panelRepo;
  private javax.swing.JTextField txtCuenta;
  // End of variables declaration//GEN-END:variables
}
